import * as monaco from "monaco-editor";

// Tokyo Night Dark Theme
export const tokyoNightTheme: monaco.editor.IStandaloneThemeData = {
  base: "vs-dark",
  inherit: true,
  rules: [
    { token: "", foreground: "c0caf5" },
    { token: "comment", foreground: "565f89" },
    { token: "keyword", foreground: "bb9af7" },
    { token: "operator", foreground: "89ddff" },
    { token: "string", foreground: "9ece6a" },
    { token: "number", foreground: "ff9e64" },
    { token: "type", foreground: "0db9d7" },
    { token: "function", foreground: "7aa2f7" },
    { token: "variable", foreground: "c0caf5" },
    { token: "variable.predefined", foreground: "c0caf5" },
    { token: "variable.parameter", foreground: "e0af68" },
    { token: "tag", foreground: "f7768e" },
    { token: "attribute.name", foreground: "bb9af7" },
    { token: "attribute.value", foreground: "9ece6a" },
    { token: "regexp", foreground: "b4f9f8" },
    { token: "markup.heading", foreground: "89ddff", fontStyle: "bold" },
    { token: "markup.italic", fontStyle: "italic" },
    { token: "markup.bold", fontStyle: "bold" },
    { token: "markup.strikethrough", fontStyle: "strikethrough" },
    { token: "markup.inserted", foreground: "73daca" },
    { token: "markup.deleted", foreground: "f7768e" },
    { token: "markup.changed", foreground: "e0af68" },
    { token: "markup.inline.code", foreground: "7dcfff" },
    { token: "markup.quote", foreground: "9ece6a", fontStyle: "italic" },
    { token: "markup.list", foreground: "c0caf5" },
    { token: "markup.link", foreground: "73daca" },
  ],
  colors: {
    "editor.background": "#1a1b26",
    "editor.foreground": "#c0caf5",
    "editorCursor.foreground": "#c0caf5",
    "editor.lineHighlightBackground": "#1e202e",
    "editorLineNumber.foreground": "#363b54",
    "editorLineNumber.activeForeground": "#787c99",
    "editor.selectionBackground": "#515c7e4d",
    "editor.inactiveSelectionBackground": "#515c7e25",
    "editorIndentGuide.background": "#232433",
    "editorIndentGuide.activeBackground": "#363b54",
    "editorWhitespace.foreground": "#363b54",
    "editorWidget.background": "#16161e",
    "editorWidget.border": "#101014",
    "editorSuggestWidget.background": "#16161e",
    "editorSuggestWidget.border": "#101014",
    "editorSuggestWidget.selectedBackground": "#20222c",
    "editorSuggestWidget.highlightForeground": "#6183bb",
    "editor.wordHighlightBackground": "#515c7e44",
    "editor.wordHighlightStrongBackground": "#515c7e55",
    "editor.findMatchBackground": "#3d59a166",
    "editor.findMatchHighlightBackground": "#3d59a166",
    "editor.findRangeHighlightBackground": "#515c7e33",
    "editorHoverWidget.background": "#16161e",
    "editorHoverWidget.border": "#101014",
    "editorOverviewRuler.border": "#101014",
    "diffEditor.insertedTextBackground": "#41a6b520",
    "diffEditor.removedTextBackground": "#db4b4b22",
  },
};

// Tokyo Night Light Theme
export const tokyoNightLightTheme: monaco.editor.IStandaloneThemeData = {
  base: "vs",
  inherit: true,
  rules: [
    { token: "", foreground: "343b58" },
    { token: "comment", foreground: "696d88" },
    { token: "keyword", foreground: "9854f1" },
    { token: "operator", foreground: "006a91" },
    { token: "string", foreground: "485e30" },
    { token: "number", foreground: "965027" },
    { token: "type", foreground: "006a91" },
    { token: "function", foreground: "2e7de9" },
    { token: "variable", foreground: "343b58" },
    { token: "variable.predefined", foreground: "343b58" },
    { token: "variable.parameter", foreground: "8f5411" },
    { token: "tag", foreground: "f52a65" },
    { token: "attribute.name", foreground: "9854f1" },
    { token: "attribute.value", foreground: "485e30" },
    { token: "regexp", foreground: "3a8ab0" },
    { token: "markup.heading", foreground: "006a91", fontStyle: "bold" },
    { token: "markup.italic", fontStyle: "italic" },
    { token: "markup.bold", fontStyle: "bold" },
    { token: "markup.strikethrough", fontStyle: "strikethrough" },
    { token: "markup.inserted", foreground: "11746f" },
    { token: "markup.deleted", foreground: "f52a65" },
    { token: "markup.changed", foreground: "8f5411" },
    { token: "markup.inline.code", foreground: "0094c4" },
    { token: "markup.quote", foreground: "485e30", fontStyle: "italic" },
    { token: "markup.list", foreground: "343b58" },
    { token: "markup.link", foreground: "11746f" },
  ],
  colors: {
    "editor.background": "#e1e2e7",
    "editor.foreground": "#343b58",
    "editorCursor.foreground": "#343b58",
    "editor.lineHighlightBackground": "#d9dadf",
    "editorLineNumber.foreground": "#9699a3",
    "editorLineNumber.activeForeground": "#1b1c23",
    "editor.selectionBackground": "#9aa5ce33",
    "editor.inactiveSelectionBackground": "#9aa5ce19",
    "editorIndentGuide.background": "#9699a320",
    "editorIndentGuide.activeBackground": "#9699a340",
    "editorWhitespace.foreground": "#9699a320",
    "editorWidget.background": "#ffffff",
    "editorWidget.border": "#d1d5da",
    "editorSuggestWidget.background": "#ffffff",
    "editorSuggestWidget.border": "#d1d5da",
    "editorSuggestWidget.selectedBackground": "#9aa5ce33",
    "editorSuggestWidget.highlightForeground": "#1c6ef7",
    "editor.wordHighlightBackground": "#9aa5ce33",
    "editor.wordHighlightStrongBackground": "#9aa5ce5a",
    "editor.findMatchBackground": "#1c6ef780",
    "editor.findMatchHighlightBackground": "#1c6ef75a",
    "editor.findRangeHighlightBackground": "#9aa5ce33",
    "editorHoverWidget.background": "#ffffff",
    "editorHoverWidget.border": "#d1d5da",
    "editorOverviewRuler.border": "#d1d5da",
    "diffEditor.insertedTextBackground": "#1c695920",
    "diffEditor.removedTextBackground": "#f52a6520",
  },
};

// Load Tokyo Night themes for Monaco editor
export function loadTokyoNightThemes(monaco: typeof import("monaco-editor")) {
  // Define themes directly without async loading
  monaco.editor.defineTheme("tokyo-night", tokyoNightTheme);
  monaco.editor.defineTheme("tokyo-night-light", tokyoNightLightTheme);

  console.log("Tokyo Night themes loaded successfully");
  return true;
}
